<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Platform.Middleware</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Platform.Abstractions\Platform.Abstractions.csproj" />
        <ProjectReference Include="..\Platform.Caching\Platform.Caching.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
        <PackageReference Include="Serilog.Enrichers.CorrelationId" Version="3.0.1" />
        <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.AspNetCore.Http" />
        <Using Include="Microsoft.Extensions.Logging" />
    </ItemGroup>

</Project>
