// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolicyService.Infrastructure.Persistence;

#nullable disable

namespace PolicyService.Infrastructure.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    partial class PolicyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("policy")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.Infrastructure.Outbox.DeadLetterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("MovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "MovedAt");

                    b.ToTable("policy_dead_letter", "policy");
                });

            modelBuilder.Entity("PolicyService.Domain.Aggregates.DebtLedgers.DebtLedger", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "ConsumerId")
                        .IsUnique();

                    b.ToTable("debt_ledgers", "policy");
                });

            modelBuilder.Entity("PolicyService.Domain.Aggregates.Policies.Policy", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CompiledRego")
                        .HasColumnType("text")
                        .HasColumnName("compiled_rego");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expression");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority_rank");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "Id");

                    b.ToTable("policies", "policy");
                });

            modelBuilder.Entity("PolicyService.Domain.Aggregates.PrincipalHierarchy.PrincipalEdge", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "UserId", "RoleId");

                    b.HasIndex("TenantId", "UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("principal_edges", "policy");
                });

            modelBuilder.Entity("PolicyService.Domain.Aggregates.PrincipalHierarchy.PrincipalNode", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer")
                        .HasColumnName("node_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "NodeId");

                    b.HasIndex("TenantId", "NodeId")
                        .IsUnique();

                    b.ToTable("principal_nodes", "policy");
                });

            modelBuilder.Entity("PolicyService.Domain.Aggregates.QuotaPolicies.QuotaPolicy", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("scope");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "Id");

                    b.ToTable("quota_policies", "policy");
                });

            modelBuilder.Entity("PolicyService.Domain.Aggregates.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "Id");

                    b.ToTable("subscriptions", "policy");
                });

            modelBuilder.Entity("PolicyService.Domain.Aggregates.UsageLedgers.UsageLedger", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "ConsumerId")
                        .IsUnique();

                    b.ToTable("usage_ledgers", "policy");
                });

            modelBuilder.Entity("SharedKernel.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProcessedAt", "NextRetryAt");

                    b.ToTable("policy_outbox", "policy");
                });

            modelBuilder.Entity("PolicyService.Domain.Aggregates.DebtLedgers.DebtLedger", b =>
                {
                    b.OwnsMany("PolicyService.Domain.ValueObjects.DebtEntry", "Debts", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("DebtLedgerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Action")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("action");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("amount");

                            b1.HasKey("TenantId", "DebtLedgerId", "Action");

                            b1.ToTable("debt_entries", "policy");

                            b1.WithOwner()
                                .HasForeignKey("TenantId", "DebtLedgerId");
                        });

                    b.OwnsMany("PolicyService.Domain.ValueObjects.RecoveryEntry", "Recoveries", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("DebtLedgerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Action")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("action");

                            b1.Property<string>("Window")
                                .HasColumnType("text")
                                .HasColumnName("window");

                            b1.Property<long>("Position")
                                .HasColumnType("bigint")
                                .HasColumnName("remaining");

                            b1.Property<DateTimeOffset>("WindowEnd")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("window_end");

                            b1.HasKey("TenantId", "DebtLedgerId", "Action", "Window");

                            b1.ToTable("recovery_entries", "policy");

                            b1.WithOwner()
                                .HasForeignKey("TenantId", "DebtLedgerId");
                        });

                    b.Navigation("Debts");

                    b.Navigation("Recoveries");
                });

            modelBuilder.Entity("PolicyService.Domain.Aggregates.QuotaPolicies.QuotaPolicy", b =>
                {
                    b.OwnsOne("PolicyService.Domain.ValueObjects.Quota", "Quota", b1 =>
                        {
                            b1.Property<Guid>("QuotaPolicyTenantId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("QuotaPolicyId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Daily")
                                .HasColumnType("bigint")
                                .HasColumnName("quota_daily");

                            b1.Property<long>("Monthly")
                                .HasColumnType("bigint")
                                .HasColumnName("quota_monthly");

                            b1.Property<long>("Weekly")
                                .HasColumnType("bigint")
                                .HasColumnName("quota_weekly");

                            b1.HasKey("QuotaPolicyTenantId", "QuotaPolicyId");

                            b1.ToTable("quota_policies", "policy");

                            b1.WithOwner()
                                .HasForeignKey("QuotaPolicyTenantId", "QuotaPolicyId");
                        });

                    b.Navigation("Quota")
                        .IsRequired();
                });

            modelBuilder.Entity("PolicyService.Domain.Aggregates.UsageLedgers.UsageLedger", b =>
                {
                    b.OwnsMany("PolicyService.Domain.ValueObjects.UsageCounter", "Counters", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UsageLedgerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Action")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("action");

                            b1.Property<string>("Window")
                                .HasColumnType("text")
                                .HasColumnName("window");

                            b1.Property<long>("Count")
                                .HasColumnType("bigint")
                                .HasColumnName("count");

                            b1.Property<DateTimeOffset>("WindowEnd")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("window_end");

                            b1.Property<DateTimeOffset>("WindowStart")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("window_start");

                            b1.HasKey("TenantId", "UsageLedgerId", "Action", "Window");

                            b1.ToTable("usage_counters", "policy");

                            b1.WithOwner()
                                .HasForeignKey("TenantId", "UsageLedgerId");
                        });

                    b.Navigation("Counters");
                });
#pragma warning restore 612, 618
        }
    }
}
