// <auto-generated />
using System;
using AuthorizationService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthorizationService.Infrastructure.Migrations
{
    [DbContext(typeof(AuthorizationDbContext))]
    [Migration("20260714145628_DropOutboxRls")]
    partial class DropOutboxRls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("authz")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthorizationService.Domain.Aggregates.Permission.Permission", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeprecatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PermissionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("Version");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("ConcurrencyVersion");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("authorization_permissions", "authz");
                });

            modelBuilder.Entity("AuthorizationService.Domain.Aggregates.PermissionGrant.PermissionGrant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "RoleId", "PermissionId");

                    b.ToTable("authorization_permission_grants", "authz");
                });

            modelBuilder.Entity("AuthorizationService.Domain.Aggregates.Role.Role", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("HierarchyDepth")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ParentRoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "DepartmentId", "Name")
                        .IsUnique();

                    b.ToTable("authorization_roles", "authz");
                });

            modelBuilder.Entity("AuthorizationService.Domain.Aggregates.RoleAssignment.RoleAssignment", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "SubjectId")
                        .IsUnique()
                        .HasFilter("\"RevokedAtUtc\" IS NULL");

                    b.HasIndex("TenantId", "SubjectId", "RoleId");

                    b.ToTable("authorization_role_assignments", "authz");
                });

            modelBuilder.Entity("AuthorizationService.Domain.Aggregates.UsageTracking.UsageTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("WindowEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_UsageTracking_TenantId");

                    b.HasIndex("WindowEnd")
                        .HasDatabaseName("IX_UsageTracking_WindowEnd");

                    b.HasIndex("TenantId", "SubjectId", "Action", "ResourceType", "ResourceId", "WindowStart", "WindowEnd")
                        .IsUnique()
                        .HasDatabaseName("IX_UsageTracking_Tenant_Subject_Action_Resource_Window");

                    b.ToTable("UsageTrackings", "authz", t =>
                        {
                            t.Property("WindowEnd")
                                .HasColumnName("UsageTracking_WindowEnd");

                            t.Property("WindowStart")
                                .HasColumnName("UsageTracking_WindowStart");
                        });
                });

            modelBuilder.Entity("Platform.Infrastructure.Outbox.DeadLetterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("MovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "MovedAt");

                    b.ToTable("authorization_dead_letter", "authz");
                });

            modelBuilder.Entity("SharedKernel.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProcessedAt", "NextRetryAt");

                    b.ToTable("authorization_outbox", "authz");
                });

            modelBuilder.Entity("AuthorizationService.Domain.Aggregates.UsageTracking.UsageTracking", b =>
                {
                    b.OwnsOne("AuthorizationService.Domain.ValueObjects.TimeWindow", "Window", b1 =>
                        {
                            b1.Property<Guid>("UsageTrackingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DurationSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("WindowDurationSeconds");

                            b1.Property<DateTimeOffset>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("WindowEnd");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("WindowStart");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("WindowType");

                            b1.HasKey("UsageTrackingId");

                            b1.ToTable("UsageTrackings", "authz");

                            b1.WithOwner()
                                .HasForeignKey("UsageTrackingId");
                        });

                    b.Navigation("Window")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
