using AuthorizationService.Application.Features.EvaluateAuthorizationDecision;

namespace AuthorizationService.Application.Features.EvaluateBatchAuthorizationDecisions;

public sealed record EvaluateBatchAuthorizationDecisionsResponse(IReadOnlyCollection<EvaluateAuthorizationDecisionResponse> Decisions);
