<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Platform.Behaviors</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Platform.Abstractions\Platform.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="12.4.1" />
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.8" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
        <PackageReference Include="Polly.Core" Version="8.5.2" />
    </ItemGroup>

</Project>
